
spring:
  application:
    name: GEA CE Platform - User & Organization Management
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 3
    password: Horschtwc3#
    url: jdbc:postgresql://db-common-services-dev.postgres.database.azure.com:5432/test
    username: postgres_admin
  flyway:
    baselineOnMigrate: true
    baselineVersion: 0.0.000
    locations: classpath:db/migration
    out-of-order: true
    schemas: test
    enabled: true